graphql:
  servlet:
    mapping: /graphql
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/


spring:
  application:
    name: user-server
  redis:
    host: redis
    port: 6379
  rabbitmq:
    host: rabbitmq
  session:
    # specify that session tokes should be stored in Redis
    store-type: redis
  datasource:
    url: "jdbc:postgresql://postgres-user:5432/postgres"
    username: "postgres"
    password: ""
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: "update"
    properties:
     hibernate.temp.use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 8080