spring:
  application:
    name: user-server
  datasource:
    url: "jdbc:h2:mem:"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "create-drop"

server:
  port: 8081


creditCardService: http://localhost:8084
orderService: http://localhost:8082