language: java
sudo: false
jdk:
- oraclejdk8
branches:
  only:
  - master
  - dev
cache:
  directories:
  - ".autoconf"
  - "$HOME/.m2"
script: mvn clean verify  -Dmaven.test.redirectTestOutputToFile=true

notifications:
  slack:
    secure: Dvp9xt6O0mtG+YNMbiVCuKB5mN6mB61pEFD+TVyc1lOpPnORPpPtOZbc/zC2KhoaqDYzitpuyQNOdmLFAxBsjuunJ3ONEwF1YU/1ofdB4TXpeT7a+wYDjOvhpHD6aTCjtLIdlnSGXnJ478y6NZVYSkLYVXPa3am8fQEkwzApE3pj8eekMSq8gkWErmYSEfUl4zLTGRzk4uhAOhxbkRxZsMIYgsEub4gBU5IuGbA1//r1aeApmNhBbam48IxeFfe7HchtNzbg5Ih3wJZDkAUePiv+brPvfjQirT1/T/2LQgVzQVW5lnNOkRLl9J/KF2aG5vTOo5iF+uOGmVcQC4gmi/g2y6/GzyWzJiD9pxvxDZLVarbUY9LdQUqm/385eGhcn5c8miuTFnqY8U9u7k8BhA5iIFjc0vSQBLEWni1/n4Ca4+lt31kdN8Li0w7EW0afRDGN4EkYbQBYWHNPktUy90pV8LCEgBJxNBDLccd1d8fLONJhqIHdxArQKk+h78JhOD/Q7I/xRB45M7avCjsFzeXKMcjG+0vQiAnXlmiiETJsxj1yhBEly1mlNfMPY2NymrLnM9Dg2XRSd6IIdZuL5BDVC8IEactyOvBp07kzkFBf4XvWD4npdn9pq/F31i8a9x41kjFb5lBKD170VZlqElHujSkE+VRVa78goIGvayU=
    on_success: always
    on_failure: always