version: '3.3'

services:

  postgres-auth:
    image: "postgres:10"
  postgres-user:
    image: "postgres:10"
  postgres-order:
    image: "postgres:10"
  postgres-movie:
    image: "postgres:10"
  postgres-creditcard:
    image: "postgres:10"
  postgres-cinema:
    image: "postgres:10"

  redis:
    image: "redis:latest"

  eureka:
    build:
      context: ./eureka
      dockerfile: Dockerfile

  auth-server:
    build:
      context: ./authentication
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-auth

  user-server:
    build:
      context: ./user
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-user


  order-server:
    build:
      context: ./order
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-order


  movie-server:
    build:
      context: ./movie
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-movie


  creditcard-server:
    build:
      context: ./creditcard
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-creditcard


  cinema-server:
    build:
      context: ./cinema
      dockerfile: Dockerfile
    depends_on:
      - redis
      - eureka
      - postgres-cinema


  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "9000:8080"
    depends_on:
      - redis
      - eureka
      - postgres-auth
      - user-server
      - order-server
      - movie-server
      - creditcard-server
      - cinema-server

# This is not complete, need to have a database for auth, later add redis and RabbitMQ, and check out of replicas, need more?

