eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: order-server
  datasource:
    url: "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1"
    driver-class-name: "org.h2.Driver"
  jpa:
    database: "h2"
    hibernate:
      ddl-auto: "validate"

server:
  port: 8082

movieService: http://localhost:8083

ticketPrice: 100

# Swagger bug, disable error for java.lang.NumberFormatException: For input string: ""
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error