spring:
  application:
    name: gateway

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
server:
  port: 8080
  servlet:
    context-path: /api/v1