eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084


# Swagger bug, disable error for java.lang.NumberFormatException: For input string: ""
logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: error