spring:
  application:
    name: gateway-server
  redis:
    host: redis
    port: 6379
  session:
    store-type: redis
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
            - POST
            - GET
            - PUT
            - PATCH
            - DELETE
            - OPTIONS
            - HEAD
      routes:
      - id: user-server
        uri: lb://user-server
        predicates:
        - Path=/user-service/**
        filters:
        - StripPrefix=1
      - id: order-server
        uri: lb://order-server
        predicates:
        - Path=/order-service/**
        filters:
        - StripPrefix=1
      - id: movie-server
        uri: lb://movie-server
        predicates:
        - Path=/movie-service/**
        filters:
        - StripPrefix=1
      - id: creditcard-server
        uri: lb://creditcard-server
        predicates:
        - Path=/creditcard-service/**
        filters:
        - StripPrefix=1
      - id: cinema-server
        uri: lb://cinema-server
        predicates:
        - Path=/cinema-service/**
        filters:
        - StripPrefix=1
      - id: auth-server
        uri: lb://auth-server
        predicates:
        - Path=/auth-service/**
        filters:
        - StripPrefix=1

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/

server:
  port: 8080